version: '3'

#https://github.com/Islandora-Devops/isle-dc/blob/development/docker-compose.traefik.yml
# Docker network create web

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.5
    container_name: reverse-proxy
    # Enables the web UI and tells Traefik to listen to docker
    command:
      - --log.level=INFO
      - --api.insecure=true
      - --entryPoints.web.address=:80
      - --entryPoints.https.address=:443
      - --entryPoints.node.address=:3000
      - --entryPoints.mysql.address=:3306
      - --entryPoints.solr.address=:8983
      - --providers.docker
      - --providers.docker.network=web
    networks:
      web: { }
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
      - "8983:8983"
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  phpmyadmin:
    image: 'phpmyadmin:latest'
    container_name: phpmyadmin
    labels:
      - traefik.enable=true
      - traefik.http.services.phpmyadmin.loadbalancer.server.port=80
      - traefik.http.routers.phpmyadmin.service=phpmyadmin
      - traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.docker.localhost`)
      - traefik.http.routers.phpmyadmin.entrypoints=web
    environment:
      - PMA_HOST=host.docker.internal
    networks:
      - web

networks:
  web:
    external: true