services:
  reverse-proxy:
    image: traefik:latest
    networks:
      web: {}
      itea: {}
      ecp: {}
      aeneas: {}
      pa-portal: {}
      solodb-onelab: {}
      solodb-tno: {}
      solodb-xenics: {}
      solodb-qutech: {}
      solodb-black-semiconductor: {}
      solodb-rayleigh: {}
      callisto: {}
      permit-manager: {}
      cebebelgica: {}
      7mntn: {}
      drukdoor: {}
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/config.yml:/etc/traefik/config.yml:ro
      # Map the certs
      - ./certs:/etc/certs:ro

  phpmyadmin:
    image: phpmyadmin:latest
    labels:
      - traefik.enable=true
      - traefik.http.services.phpmyadmin.loadbalancer.server.port=80
      - traefik.http.routers.phpmyadmin.service=phpmyadmin
      - traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.docker.localhost`)
      - traefik.http.routers.phpmyadmin.entrypoints=https
      - traefik.http.routers.phpmyadmin.tls=true
    environment:
      - PMA_HOST=mysql
    networks:
      - web

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    logging:
      driver: "none" # disable saving logs
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui
    networks:
      - web

  mysql:
    image: ghcr.io/jield-webdev/docker-repos/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - web

volumes:
  docker-mysql-volume:
  mysql-data:

networks:
  web:
    external: true
  itea:
    external: true
  ecp:
    external: true
  aeneas:
    external: true
  pa-portal:
    external: true
  solodb-xenics:
    external: true
  solodb-onelab:
    external: true
  solodb-qutech:
    external: true
  solodb-rayleigh:
    external: true
  solodb-black-semiconductor:
    external: true
  solodb-tno:
    external: true
  callisto:
    external: true
  permit-manager:
    external: true
  cebebelgica:
    external: true
  7mntn:
    external: true
  drukdoor:
    external: true
